### PR TITLE
move logic to onMount

### PR DESCRIPTION
**Pull request by nosovk**

### CODE REVIEW

**Comment by nosovk** [comment]
Currently intersection observer not always initialized after hydration.
For example - https://github.com/MailCheck-co/mailcheck.site/blob/master/src/components/Partners.svelte
It's live on https://www.mailcheck.co/ - if you will start scrolling during load it will never trigger.
Proposed solution is to move logic to onMount, which surely works only in browser.

**Comment by metonym** [comment]
Interesting. Are you sure it's not because it intersected with `once` triggering the `unobserve` logic?

https://github.com/metonym/svelte-intersection-observer/blob/master/src/IntersectionObserver.svelte#L61

**Comment by nosovk** [comment]
hm, doesnt seem like that. It seems that it's not inited at all, rather then unobserverd to fast

**Comment by metonym** [comment]
I'll take a look

**Review by metonym — CHANGES_REQUESTED** [review]
Requested changes:

- move `onDestroy` logic into the returned callback in `onMount`
- remove the `onDestroy` import

**Review by metonym — APPROVED** [review]
Looks good, thanks

**Comment by metonym** [comment]
@nosovk  Released in v0.6.1

**Comment by nosovk** [comment]
It seems that it didn't help and problem still persists. Time to time intersection observer does not init. It causes problem that some elements never shown as a result.

**Pull request merged**
