### PR TITLE
support dynamically changing the rootMargin

### PR DESCRIPTION
**Pull request by dysfunc**
Allows for updating `rootMargin` after init to accommodate scrolling, zooming, network, etc. changes.

There's a discussion happening around this currently with the W3C IO Spec. It sounds like it will eventually be supported, but is not something currently provided.

https://github.com/w3c/IntersectionObserver/issues/428

Thoughts?

### CODE REVIEW

**Comment by metonym** [comment]
What's your use case? Can you provide some code?

**Comment by dysfunc** [comment]
Scenario:
- I have a container element that has N child nodes. 
- Each child node is tracked using IO to determine viewability.
- The child elements also dynamically change scale on zooming/pinch-zoom gesture occurs using CSS transforms. When scaled down past a certain threshold the `rootMargin` needs to be adjusted to accurately detect the correct element.

**Comment by metonym** [comment]
And why not use the `#key` API to recreate the component if the root margin changes?

**Comment by dysfunc** [comment]
Using `#key` satisfies simple cases where you can afford to destroy and recreate static elements. Applying `#key` to anything dynamic will reset when `rootMargin` changes.

**Comment by metonym** [comment]
I'll take another look at this – I agree that updating the root margin can be a common enough use case.

**Review by metonym — APPROVED** [review]
Thank you for keeping this up to date. Tested locally and it works great.

**Comment by metonym** [comment]
Published to NPM in [version 0.7.0](https://github.com/metonym/svelte-intersection-observer/releases/tag/v0.7.0)

**Comment by ysfcbn** [comment]
I need to use it with JavaScript. can you help me please for convert this code JS syntax?

**Pull request merged**
